/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sandeepsingh' at '5/11/16 11:07 AM' with Gradle 2.9
 *
 * @author sandeepsingh, @date 5/11/16 11:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
